---
- name: installing tools on master
  hosts: localhost
  become: true
  tasks: 
  - name: executing master.sh script
    script: master.sh
- name: installing tools on slaves
  hosts: slave1
  become: true
  tasks: 
  - name: executing slave.sh script
    script: slave.sh
- name: installing tools on slaves
  hosts: slave2
  become: true
  tasks: 
  - name: executing slave.sh script
    script: slave.sh	  
